Ejercicio de Big Data
rilopez/big-data-exercises pull request #40
Opened 2018-04-07 07:09 UTC by raraizan

Se agrega el Ejercicio de Big Data

2018-04-07 08:41 UTC, raraizan commented
Hice una correccion, habia subido un archivo no actualizado

2018-04-09 22:39 UTC, blzb requested changes
La carpeta .idea deberia ir en el gitignore

2018-04-16 02:38 UTC, emoteNS commented on src/test/java/nearsoft/academy/bigdata/recommendation/MovieRecommender.java
> +import java.io.*;
Avoid using wildcard imports :)

2018-04-16 03:10 UTC, emoteNS commented on src/test/java/nearsoft/academy/bigdata/recommendation/MovieRecommender.java
> +            System.out.println("Procesando el archivo...");
You can use a Logger instead of sout :)

2018-04-16 03:27 UTC, emoteNS commented on src/test/java/nearsoft/academy/bigdata/recommendation/MovieRecommender.java
> +    private int totalReviews = 0;
You may not initialize the value of this variable here, because the default value for an int as a member class is 0 :)

2018-04-16 03:28 UTC, emoteNS commented on src/test/java/nearsoft/academy/bigdata/recommendation/MovieRecommender.java
> +            BufferedWriter bw = new BufferedWriter(new FileWriter("cleanedFile.csv"));
I recommend use String constants to avoiding problems with literals :)

2018-04-16 03:30 UTC, emoteNS commented on src/test/java/nearsoft/academy/bigdata/recommendation/MovieRecommender.java
> +        List<String> output = new ArrayList();
For many add operations, you may consider a `LinkedList` instead of `ArrayList`

2018-04-16 03:34 UTC, emoteNS commented on src/test/java/nearsoft/academy/bigdata/recommendation/MovieRecommender.java
> +            recommendations = recommender.recommend(Long.parseLong(users.get(userID)), 3);
I would recommend to research it and put your results :) You can check on the recommender API documentation

2018-08-28 22:18 UTC, closed without merging